console.log(Boolean(''));
console.log(Boolean('fdkfd'));
console.log(Boolean(0));
console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(Boolean(undefined));
console.log(Boolean(NaN));
console.log(Boolean(54));
console.log(Boolean(-45));
